name: cct001

description: "A new Flutter project."
# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  confirm_dialog: ^1.0.3
  flutter_dotenv: ^5.1.0
  http: ^1.2.1
  logger: ^2.3.0  
  fluttertoast: ^8.2.6 
  flutter_launcher_icons: "^0.13.1"
  provider: ^6.0.1
  flutter_secure_storage: ^9.2.2
  flutter_native_splash: ^2.4.1
  sqflite: ^2.3.3+1
  path_provider: ^2.0.5 
  firebase_core: ^3.2.0
  firebase_messaging: ^15.0.3 
  firebase_analytics: ^11.2.0
  firebase_crashlytics: ^4.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/  
    - config/.env
flutter_native_splash: 
  color: "#42a5f5"