name: grx003

description: "A new Flutter project."
# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 2.0.11+11

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  confirm_dialog: ^1.0.3
  flutter_dotenv: ^5.1.0
  http: ^1.2.1
  logger: ^2.3.0
  fluttertoast: ^8.2.6
  flutter_launcher_icons: ^0.14.1
  provider: ^6.0.1
  flutter_secure_storage: ^9.2.2
  sqflite: ^2.3.3+1
  path_provider: ^2.0.5
  firebase_core: ^3.2.0
  firebase_messaging: ^15.0.3
  firebase_analytics: ^11.2.0
  firebase_crashlytics: ^4.0.3
  flutter_spinkit: ^5.2.1
  prompt_dialog: ^1.0.16
  latlong2: ^0.9.1
  flutter_map_math: ^0.1.7
  shared_preferences: ^2.3.1
  url_launcher: ^6.3.1
  card_widget: ^0.0.6
  keep_screen_on: ^3.0.0
  flutter_map: ^7.0.2
  location: ^7.0.0
  flutter_map_cancellable_tile_provider: ^3.0.0
  flutter_native_splash: ^2.4.1
  intl: ^0.19.0
  flutter_staggered_grid_view: ^0.7.0
  device_info_plus: ^11.1.1
  uuid: ^4.5.0
  crypto: ^3.0.5
  flutter_speed_dial: ^7.0.0
  dio: ^5.5.0+1 #ZMT added
  jwt_decoder: ^2.0.1 #ZMT added
  oauth2: ^2.0.2 #ZMT added
  webview_flutter: ^4.4.2 #ZMT added
  geocoding: ^3.0.0
  pin_code_fields: ^8.0.1
  web_socket_channel: ^3.0.1
  flutter_polyline_points: ^2.1.0
  connectivity_plus: ^6.0.5
  fl_chart: ^0.69.0
  pull_to_refresh: ^2.0.0
  cached_network_image: ^3.4.1
  stomp_dart_client: ^2.1.0
  google_maps_flutter: ^2.9.0
  image_picker: ^1.1.2
  image_cropper: ^8.0.2
  permission_handler: ^11.3.1
  


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/geo/
    - assets/images/
    - assets/images/social/
    - lib/src/message/
  fonts:
    - family: Digital
      fonts:
        - asset: assets/fonts/digital-7.ttf

#dart pub run flutter_native_splash:create
#dart pub run flutter_native_splash:remove
flutter_native_splash:
  color: "#ffffff"
  image: assets/images/loading/wait01.png
  android_12:
    image: assets/images/loading/wait02.png
    icon_background_color: "#ffffff"
