name: cct001

description: "A new Flutter project."
# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  confirm_dialog: ^1.0.3
  flutter_dotenv: ^5.1.0
  http: ^1.2.1
  logger: ^2.3.0  
  fluttertoast: ^8.2.6 
  flutter_launcher_icons: "^0.13.1"
  provider: ^6.0.1
  flutter_secure_storage: ^9.2.2
  sqflite: ^2.3.3+1
  path_provider: ^2.0.5 
  firebase_core: ^3.2.0
  firebase_messaging: ^15.0.3 
  firebase_analytics: ^11.2.0
  firebase_crashlytics: ^4.0.3
  flutter_spinkit: ^5.2.1
  prompt_dialog: ^1.0.16
  latlong2: ^0.9.1
  flutter_map_math: ^0.1.7
  shared_preferences: ^2.3.1
  url_launcher: ^6.3.0
  card_widget: ^0.0.6
  keep_screen_on: ^3.0.0
  flutter_map: ^7.0.2
  location: ^7.0.0
  flutter_map_cancellable_tile_provider: ^3.0.0
  flutter_native_splash: ^2.4.1
  


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/geo/
    - assets/images/


#dart pub run flutter_native_splash:create
#dart pub run flutter_native_splash:remove
flutter_native_splash:
  color: "#ffffff"
  image: assets/images/loading/wait01.png
  android_12:
    image: assets/images/loading/wait02.png
    icon_background_color: "#ffffff"